### ISSUE TITLE
Shamelessly stolen from https://github.com/Laximas/vue3-steppy

### ISSUE THREAD

**Issue by Tofandel** [PiusLucky/vue3-multi-stepper#3]
A minimum of attribution or just contributing to the original project which is still active would have been the right thing to do

https://github.com/Laximas/vue3-steppy

**Comment by PiusLucky** [comment]
Sorry you didnt see this.
![image](https://github.com/PiusLucky/vue3-multi-stepper/assets/32282934/10e2b3a8-52cf-494e-a3e0-267b472d9793)
